### ISSUE TITLE
Help initial run in mac

### ISSUE THREAD

**Issue by bishalkc** [IBM/build-blockchain-insurance-app#120]
I am trying to get the app running in mac, I had to make couple changes on CA_TAG and FABRIC_TAG to point recent tags with that i can now run ./build-mac.sh. It creates all the images however getting stuck here. Any help/direction will be highly appreciated. 

> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.
Successfully installed chaincode on the default channel.
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: error in simulation: could not launch chaincode bcins:v2: error building chaincode: error building image: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "/chaincode/input/src/bcins/data.go:8:2: cannot find package "github.com/hyperledger/fabric/core/chaincode/shim" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
	/go/src/github.com/hyperledger/fabric/core/chaincode/shim
/chaincode/input/src/bcins/invoke_insurance.go:11:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
	/go/src/github.com/hyperledger/fabric/protos/peer
"
    at /app/www/blockchain/utils.js:252:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:107:191)
    at /app/bin/blockchain/utils.js:107:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by xianfuhui** [comment]
i too on ubuntu :(
