### ISSUE TITLE
Failed to start WEB correctly and localhost:3000 throws internal server issue

### ISSUE THREAD

**Issue by vr357h** [IBM/build-blockchain-insurance-app#13]
Here is the log..

Server running on port: 3000
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"insurance-peer","grpc.default_authority":"insurance-peer"}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"shop-peer","grpc.default_authority":"shop-peer"}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"repairshop-peer","grpc.default_authority":"repairshop-peer"}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"police-peer","grpc.default_authority":"police-peer"}
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
Successfully instantiated chaincode on all peers.
TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/app/node_modules/pug-parser/index.js:776:23)
    at Parser.parseExpr (/app/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/app/node_modules/pug-parser/index.js:112:25)
    at parse (/app/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/app/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/app/node_modules/pug-load/index.js:45:21)
    at compileBody (/app/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/app/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/app/node_modules/pug/lib/index.js:216:25)
    at Object.exports.renderFile (/app/node_modules/pug/lib/index.js:428:10)
TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/app/node_modules/pug-parser/index.js:776:23)
    at Parser.parseExpr (/app/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/app/node_modules/pug-parser/index.js:112:25)
    at parse (/app/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/app/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/app/node_modules/pug-load/index.js:45:21)
    at compileBody (/app/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/app/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/app/node_modules/pug/lib/index.js:216:25)
    at Object.exports.renderFile (/app/node_modules/pug/lib/index.js:428:10)

Thank in advance for looking into this!!

**Comment by ishangulhane** [comment]
@vr357h I not able to replicate the issue. Follow the troubleshooting steps to clean the network and then try to set up the network again.

**Comment by ljbennett62** [comment]
@vr357h - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
