### ISSUE TITLE
Local Setup of Project in Ubuntu Web is crashing

### ISSUE THREAD

**Issue by durgeshkesharideva1** [IBM/build-blockchain-insurance-app#137]
Hello Community,
i tired to setup this project locally in Ubuntu system.
But the web container is getting crash in just 10 seconds.

Here is the logs:
`
> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'map' of undefined
(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Successfully installed chaincode on the default channel.
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: error in simulation: could not launch chaincode bcins:v2: error building chaincode: error building image: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "chaincode/input/src/bcins/data.go:8:2: cannot find package "github.com/hyperledger/fabric/core/chaincode/shim" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
chaincode/input/src/bcins/invoke_insurance.go:11:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
"
    at /app/www/blockchain/utils.js:252:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:107:191)
    at /app/bin/blockchain/utils.js:107:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-01-06T14_35_18_607Z-debug.log
`

I'm not sure what should I do.

kindly can anyone can guide to fix this issue and get start.

Thanks in Advance.

**Comment by lu-jumba** [comment]
Consider looking at the fabric samples on how the life cycle has changed since this project was written. You may need to up date/re-write some files
