### ISSUE TITLE
Cannot find Package github.com/hyperledger/fabric/core/chaincode/shim

### ISSUE THREAD

**Issue by golepavan** [IBM/build-blockchain-insurance-app#138]
Error: Proposal rejected by some (all) of the peers: Error: error in simulation: could not launch chaincode bcins:v2: error building chaincode: error building image: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "chaincode/input/src/bcins/data.go:8:2: cannot find package "github.com/hyperledger/fabric/core/chaincode/shim" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
chaincode/input/src/bcins/invoke_insurance.go:11:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
"
    at /app/www/blockchain/utils.js:252:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:107:191)
    at /app/bin/blockchain/utils.js:107:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-29T19_29_30_212Z-debug.log

root@ip-172-31-32-206 build-blockchain-insurance-app# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@ip-172-31-32-206:/build-blockchain-insurance-app# docker --version
Docker version 18.09.6, build 481bc77
root@ip-172-31-32-206:/build-blockchain-insurance-app# docker-compose --version
docker-compose version 1.24.0, build 0aa59064
root@ip-172-31-32-206:build-blockchain-insurance-app#

**Comment by lu-jumba** [comment]
Now the packages used are github.com/hyperledger/fabric-chaincode-go/shim and github.com/hyperledger/fabric-protos-go/peer
