### ISSUE TITLE
cert and key do not match

### ISSUE THREAD

**Issue by nemat0098** [IBM/build-blockchain-insurance-app#139]
2024-07-16 22:49:45.347 UTC 0004 INFO [peer] getLocalAddress -> Auto-detected peer address: 172.19.0.10:7051
2024-07-16 22:49:45.347 UTC 0005 INFO [peer] getLocalAddress -> Returning police-peer:7051
2024-07-16 22:49:45.348 UTC 0006 INFO [nodeCmd] initGrpcSemaphores -> concurrency limit for endorser service is 2500
2024-07-16 22:49:45.348 UTC 0007 INFO [nodeCmd] initGrpcSemaphores -> concurrency limit for deliver service is 2500
2024-07-16 22:49:45.348 UTC 0008 INFO [nodeCmd] initGrpcSemaphores -> concurrency limit for gateway service is 500
2024-07-16 22:49:45.348 UTC 0009 INFO [nodeCmd] serve -> Starting peer with TLS enabled
2024-07-16 22:49:45.348 UTC 000a FATA [nodeCmd] serve -> Failed to set TLS client certificate (error parsing client TLS key pair: tls: private key does not match public key)

**i have this problem in docker at police-peer repairshop-peer shop-peer police-ca
and another error in web container that follows bottom massage**

2024-07-17 02:18:57 Fatal error logging into blockchain organization clients!
2024-07-17 02:18:57 Error: Could not get UserContext! Error: Failed to enroll and persist User. Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND police-ca police-ca:7054]
2024-07-17 02:18:57     at /app/www/blockchain/utils.js:448:11
2024-07-17 02:18:57     at Generator.throw (<anonymous>)
2024-07-17 02:18:57     at step (/app/bin/blockchain/utils.js:107:191)
2024-07-17 02:18:57     at /app/bin/blockchain/utils.js:107:402
2024-07-17 02:18:57     at <anonymous>
2024-07-17 02:18:57     at process._tickCallback (internal/process/next_tick.js:188:7)
2024-07-17 02:19:44 
2024-07-17 02:19:44 > blockchain-for-insurance@2.1.1 serve /app
2024-07-17 02:19:44 > cross-env NODE_ENV=production&&node ./bin/server
2024-07-17 02:19:44 
2024-07-17 02:19:44 Wallet path: /app/www/blockchain/wallet
2024-07-17 02:19:45 /app/app/static/js
2024-07-17 02:19:45 Server running on port: 3000
2024-07-17 02:19:47 Failed to enroll user. Error: Could not get UserContext! Error: Failed to enroll and persist User. Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND police-ca police-ca:7054]
2024-07-17 02:19:47 Fatal error logging into blockchain organization clients!
2024-07-17 02:19:47 Error: Could not get UserContext! Error: Failed to enroll and persist User. Error: Calling enrollment endpoint failed with error [Error: getaddrinfo ENOTFOUND police-ca police-ca:7054]
2024-07-17 02:19:47     at /app/www/blockchain/utils.js:448:11
2024-07-17 02:19:47     at Generator.throw (<anonymous>)
2024-07-17 02:19:47     at step (/app/bin/blockchain/utils.js:107:191)
2024-07-17 02:19:47     at /app/bin/blockchain/utils.js:107:402
2024-07-17 02:19:47     at <anonymous>
2024-07-17 02:19:47     at process._tickCallback (internal/process/next_tick.js:188:7)

**its just too long i just take some of it
any solution?**
![Screenshot 2024-07-17 033709](https://github.com/user-attachments/assets/b00a6067-ab19-403b-adfc-80e391e6fedf)
![Screenshot 2024-07-17 033652](https://github.com/user-attachments/assets/bd670057-9f07-4c49-85e7-681ef6d5e354)

**Comment by nemat0098** [comment]
btw i do it locally
and is this going to be modified to another language?
can i change it?
