### ISSUE TITLE
No signing identity while using client.query method

### ISSUE THREAD

**Issue by trinayanbhatt** [IBM/build-blockchain-insurance-app#80]
I just made query from the blockchain network using fabric-client's query method but i got this error:

`Error: No identity has been assigned to this client
    at Client._getSigningIdentity (/node_modules/fabric-client/lib/Client.js:1290:11)
    at Client.newTransactionID (/node_modules/fabric-client/lib/Client.js:645:33)
`
Please help to resolve this issue.

**Comment by varunagarwal315** [comment]
Did you initiate the client properly and use `new User({ })` constructor or import a user details from a wallet? Can you share the relevant code snippet you wrote.
