### ISSUE TITLE
"Could not create new contract!" on local

### ISSUE THREAD

**Issue by taynguyen** [IBM/build-blockchain-insurance-app#81]
I followed the installation for local set up.
I was able to start web but failed to "Order" when making an payment at bike shop.

The web log is:
```
> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Peer joined default channel
Peer joined default channel
Peer joined default channel
Peer joined default channel
(node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /app/www/routers/shop.router.js:49:19
    at Generator.next (<anonymous>)
    at step (/app/bin/routers/shop.router.js:20:191)
    at /app/bin/routers/shop.router.js:20:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.
Successfully installed chaincode on the default channel.
(node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /app/www/routers/shop.router.js:49:19
    at Generator.next (<anonymous>)
    at step (/app/bin/routers/shop.router.js:20:191)
    at /app/bin/routers/shop.router.js:20:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Successfully instantiated chaincode on all peers.
args in shopPeer query: { shopType: 'B' }
func in shopPeer query: 'contract_type_ls'
invokeCC called, function: contract_type_ls and the args:
{ shopType: 'B' }
An identity for the user shopApp-admin does not exist in the wallet
Run the registerUser.js application before retrying
Failed to submit transaction: TypeError: Cannot set property 'error' of undefined
args in shopPeer query: { shopType: 'B' }
func in shopPeer query: 'contract_type_ls'
invokeCC called, function: contract_type_ls and the args:
{ shopType: 'B' }
An identity for the user shopApp-admin does not exist in the wallet
Run the registerUser.js application before retrying
Failed to submit transaction: TypeError: Cannot set property 'error' of undefined
args in shopPeer query: { shopType: 'B' }
func in shopPeer query: 'contract_type_ls'
invokeCC called, function: contract_type_ls and the args:
{ shopType: 'B' }
An identity for the user shopApp-admin does not exist in the wallet
Failed to submit transaction: TypeError: Cannot set property 'error' of undefined
Run the registerUser.js application before retrying
contract before ojbect.assign: [object Object]
contract after object.assign: [object Object]
args in shopPeer invoke: { contractTypeUuid: '1d640cf7-9808-4c78-b7f0-55aaad02e9e5',
  username: '',
  password: 'demo62',
  firstName: '',
  lastName: '',
  item:
   { id: 0,
     brand: 'Canyon',
     model: 'Spectral AL 6.0',
     price: 3420,
     serialNo: 'JJR2Q9' },
  startDate: '1970-01-01T00:00:00.000Z',
  endDate: '1970-01-01T00:00:00.000Z',
  uuid: '02074b20-0af5-4109-999f-c9da79a18316' }
func in shopPeer invoke: 'contract_create'
invokeCC called, function: contract_create and the args:
{ contractTypeUuid: '1d640cf7-9808-4c78-b7f0-55aaad02e9e5',
  username: '',
  password: 'demo62',
  firstName: '',
  lastName: '',
  item:
   { id: 0,
     brand: 'Canyon',
     model: 'Spectral AL 6.0',
     price: 3420,
     serialNo: 'JJR2Q9' },
  startDate: '1970-01-01T00:00:00.000Z',
  endDate: '1970-01-01T00:00:00.000Z',
  uuid: '02074b20-0af5-4109-999f-c9da79a18316' }
An identity for the user shopApp-admin does not exist in the wallet
Run the registerUser.js application before retrying
Failed to submit transaction: TypeError: Cannot set property 'error' of undefined
Error creating contract: Proposal rejected by some (all) of the peers: Error: User with this username does not exist.
{ Error: Error creating contract: Proposal rejected by some (all) of the peers: Error: User with this username does not exist.
    at wrapError (/app/www/blockchain/utils.js:444:15)
    at Object.<anonymous> (/app/www/blockchain/shopPeer.js:42:11)
    at Generator.throw (<anonymous>)
    at step (/app/bin/blockchain/shopPeer.js:180:191)
    at /app/bin/blockchain/shopPeer.js:180:402
    at <anonymous>
  inner: Error: Proposal rejected by some (all) of the peers: Error: User with this username does not exist.
    at /app/www/blockchain/utils.js:305:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:103:191)
    at /app/bin/blockchain/utils.js:103:361
    at <anonymous> }

**Comment by horeaporutiu** [comment]
and did you do this step - https://github.com/IBM/build-blockchain-insurance-app#step-9-enroll-app-admin-identities - where you should have the shopApp-admin identity in your wallet directory?

**Comment by taynguyen** [comment]
@horeaporutiu : No I haven't execute step 9. It was not mention in guide for LOCAL environment? I would make a try with step 9.
