### ISSUE TITLE
I cannot instantiate a chaincode on all peers.Can someone check it out for me?

### ISSUE THREAD

**Issue by TengMa-A** [IBM/build-blockchain-insurance-app#94]
> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Peer joined default channel
Peer joined default channel
Peer joined default channel
Peer joined default channel
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.
Successfully installed chaincode on the default channel.
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'map' of undefined
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: REQUEST_TIMEOUT
    at /app/www/blockchain/utils.js:252:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:107:191)
    at /app/bin/blockchain/utils.js:107:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-12-05T02:08:55.420Z - error: [Peer.js]: sendProposal - timed out after:45000
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-05T02_08_56_002Z-debug.log

I have modified the Dockerfile by referring to other people's problems, but it still cannot run

**Comment by TengMa-A** [comment]
The problem has been solved. The reason for the problem is that my docker version is not 18.09.6
